### ISSUE TITLE
Pat Simmons audio files

### ISSUE THREAD

**Issue by mcjoshea** [paulseward/asterisk-tim#4]
Hi Paul, 

I was looking at getting a Pat Simmons speaking clock running today so downloaded all your files.

There unfortunately seems to be a problem with _all_ the hour files. I can't get _any_ of them to play with VLC.  

![image](https://user-images.githubusercontent.com/63942949/146662792-3b920a72-3ef4-4419-89cc-0a40b4bb24d9.png)

When unpacked, each of the hour files are just 6 byte in size. There's a similar issue with the_phrase.wav file, which unpacks to just 34 bytes. I've tried the different versions available and they have the same issue. 

Would you be able to re-upload the faulty files?

Thanks 
Mark

**Comment by paulseward** [comment]
Hi. 

those aren’t “real” files, they’re symbolic links (pointers to other files in the download package) which are used by the linux file system that asterisk runs on to provide an abstraction layer between what asterisk calls the wav file and what I called the recordings.

I assume you’re using windows, which can’t follow symbolic links.

You’ll need to use the underlying files instead, eg “01.wav” file for “hour-01.wav” etc.  “The phrase” is what the gpo called “at the third stroke”

I won’t be “re-uploading the broken files” because they’re not actually broken, and duplication of data isn’t desirable.

hope that helps!

-Paul

**Comment by mcjoshea** [comment]
Thanks Paul. You were right. I was checking the files on my Windows computer before attempting to install them on my FreePBX box.  

The reason I never twigged about the missing files being symbolic links was that I thought Pat recorded the hours with a different intonation to the minutes.

This might help someone else in the future. It's how I installed TIM on FreePBX v15.0.

```
yum install git
cd /etc/asterisk
git clone https://github.com/paulseward/asterisk-tim.git
ln -s /etc/asterisk/asterisk-tim/Audio /var/lib/asterisk/sounds/TIM
```

I then edited: `/etc/asterisk/extensions.conf`
and added this line: `#include /etc/asterisk/asterisk-tim/tim.conf`

Next I edited this: `/etc/asterisk/extensions_custom.conf` and added this:
```
[speakingclock]
exten => 123,1,Gosub(TIM,s,1(${PAT}))
```
Then, in the FreePBX web interface, I added a _Custom Destination_ with these details:
>Target: speakingclock,123,1
>Description: Speaking Clock

I also had to create a _virtual extension_ in the web interface:

> Extension: 123
> Name: Speaking Clock
> Advanced - Optional Destinations - All options set to _Custom Destinations_ and _Speaking Clock_

And after that I can now dial 123 and listen to Pat Simmons tell me the time!

It's wonderful to be able to hear the old Speaking Clock once again. Thanks for all the hard work you put into creating this.

Cheers
Mark
